name: Angular Project CI/CD

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Build the project"
        required: true
        default: "true"
      lint:
        description: "Lint the project"
        required: true
        default: "true"
  push:
    branches:
      - main
  issues:
    types: [opened, edited, closed]
  pull_request:
    types: [opened, edited, closed]

jobs:
  handle_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

  handle_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  handle_issue_open:
    if: github.event_name == 'issues' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Issue Message
        run: echo "Issue opened"
  handle_pr_open:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: PR Message
        run: echo "PR opened"
